### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by shkarupa-alex** [nnizhang/SMAC#1]
Could you please publish your dataset somewhere outside of baidu? Maybe google drive...
Baidu is not accessible from my country

**Comment by nnizhang** [comment]
I have uploaded it to the google drive. The link is https://drive.google.com/file/d/1PM8wo8xFrHK2oVpYz_9aON6Imc_SM5Cl/view?usp=sharing. Please check.

**Comment by shkarupa-alex** [comment]
It's ok.
Thanks.
