### ISSUE TITLE
Computing global and interior Contrast

### ISSUE THREAD

**Issue by geyan21** [nnizhang/SMAC#3]
Your work is very inspiring! Can you provide the code of computing global and interior Contrast?

**Comment by nnizhang** [comment]
Thank you for your interest. I have uploaded the codes. I hope it will help you.

**Comment by Geekyange** [comment]
Thank you so much! Could you please provide the code for computing depth quality? I am a beginner now and I'm very willing to learn your code.

**Comment by Geekyange** [comment]
> Thank you for your interest. I have uploaded the codes. I hope it will help you.



> Thank you for your interest. I have uploaded the codes. I hope it will help you.

Thank you so much! Could you please provide the code for computing depth quality? I am a beginner now and I'm very willing to learn your code.
